### ISSUE TITLE
How to insert data to the accountmapping

### ISSUE THREAD

**Issue by murunwas** [introtocomputerscience/EntityFrameworkExample#2]
thanks for this repo, can you please help me how to add account and user using the accountmapping if possible

**Comment by rawrspace** [comment]
Hi murunwas,

I added a method called PostUser and a method called PostAccount showing how to do this. Please see the updated controller here: https://github.com/introtocomputerscience/EntityFrameworkExample/blob/master/UnitOfWorkRepositoryExample/UnitOfWorkRepositoryExample/Controllers/ExampleController.cs

**Comment by murunwas** [comment]
thanks alot @vandersmissenc for sharing
