### ISSUE TITLE
Getting error trying updating Users and accounts using many to many

### ISSUE THREAD

**Issue by murunwas** [introtocomputerscience/EntityFrameworkExample#3]
When I try to update Users and their accounts, I get "A referential integrity constraint violation occurred: The property values that define the referential constraints are not consistent between principal and dependent objects in the relationship." can you please help how to fix this issue?? thanks @vandersmissenc

**Comment by rawrspace** [comment]
I will check it out hopefully tomorrow and provide an update.

**Comment by rawrspace** [comment]
After looking into this issue I was not able to replicate it on my machine. Can you please elaborate on the actions you took to cause the message?
